library(ggplot2)
library(plotly)

regions = c("Global",
            "Argentina",
            "Australia",
            "Austria",
            "Belgium",
            "Bolivia",
            "Brazil",
            "Canada",
            "Chile",
            "Colombia",
            "Costa Rica",
            "Czech Republic",
            "Denmark",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Estonia",
            "Finland",
            "France",
            "Germany",
            "Greece",
            "Guatemala",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Ireland",
            "Israel",
            "Italy",
            "Japan",
            "Latvia",
            "Lithuania",
            "Malaysia",
            "Mexico",
            "Morocco",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Norway",
            "Panama",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Romania",
            "Russia",
            "Saudi Arabia",
            "Singapore",
            "Slovakia",
            "South Africa",
            "South Korea",
            "Spain",
            "Sweden",
            "Switzerland",
            "Taiwan",
            "Thailand",
            "Turkey",
            "Ukraine",
            "United Arab Emirates",
            "United States",
            "Uruguay",
            "Vietnam")

top_artists_ui <- 
  tabPanel("Top artists by year",
           fluidPage(
             fluidPage(
               column(6, 
                 tags$div(class='select',
                          selectInput("top_artists_region",
                                      "Region",
                                      regions,
                                      selected="Global",
                                      width="100%")), 
                 ),
               column(6, 
                      tags$div(class='select',
                               selectInput("top_artists_year",
                                           "Year",
                                           c("2017", "2018", "2019", "2020", "2021"),
                                           selected="2017",
                                           width="100%")), 
               )
             ),
             plotlyOutput('top_artists_by_year') %>% withSpinner(color = "#1CB752")
           )
  )

